// Level Actions
export const FETCH_LEVELS = 'FETCH_LEVELS';
export const FETCH_LEVELS_SUCCESS = 'FETCH_LEVELS_SUCCESS';
export const FETCH_LEVELS_ERROR = 'FETCH_LEVELS_ERROR';

export const CREATE_LEVEL = 'CREATE_LEVEL';
export const CREATE_LEVEL_SUCCESS = 'CREATE_LEVEL_SUCCESS';
export const CREATE_LEVEL_ERROR = 'CREATE_LEVEL_ERROR';

export const UPDATE_LEVEL = 'UPDATE_LEVEL';
export const UPDATE_LEVEL_SUCCESS = 'UPDATE_LEVEL_SUCCESS';
export const UPDATE_LEVEL_ERROR = 'UPDATE_LEVEL_ERROR';

export const DELETE_LEVEL = 'DELETE_LEVEL';
export const DELETE_LEVEL_SUCCESS = 'DELETE_LEVEL_SUCCESS';
export const DELETE_LEVEL_ERROR = 'DELETE_LEVEL_ERROR';

// Batch operations
export const BATCH_UPDATE_LEVELS = 'BATCH_UPDATE_LEVELS';
export const BATCH_UPDATE_LEVELS_SUCCESS = 'BATCH_UPDATE_LEVELS_SUCCESS';
export const BATCH_UPDATE_LEVELS_ERROR = 'BATCH_UPDATE_LEVELS_ERROR';
