// Memberships Action Types
export const FETCH_MEMBERSHIPS = "FETCH_MEMBERSHIPS";
export const FETCH_MEMBERSHIPS_SUCCESS = "FETCH_MEMBERSHIPS_SUCCESS";
export const FETCH_MEMBERSHIPS_ERROR = "FETCH_MEMBERSHIPS_ERROR";

export const CREATE_MEMBERSHIP = "CREATE_MEMBERSHIP";
export const CREATE_MEMBERSHIP_SUCCESS = "CREATE_MEMBERSHIP_SUCCESS";
export const CREATE_MEMBERSHIP_ERROR = "CREATE_MEMBERSHIP_ERROR";

export const UPDATE_MEMBERSHIP = "UPDATE_MEMBERSHIP";
export const UPDATE_MEMBERSHIP_SUCCESS = "UPDATE_MEMBERSHIP_SUCCESS";
export const UPDATE_MEMBERSHIP_ERROR = "UPDATE_MEMBERSHIP_ERROR";

export const DELETE_MEMBERSHIP = "DELETE_MEMBERSHIP";
export const DELETE_MEMBERSHIP_SUCCESS = "DELETE_MEMBERSHIP_SUCCESS";
export const DELETE_MEMBERSHIP_ERROR = "DELETE_MEMBERSHIP_ERROR";
