export const FETCH_MEMBERS = "FETCH_MEMBERS";
export const FETCH_MEMBERS_SUCCESS = "FETCH_MEMBERS_SUCCESS";
export const FETCH_MEMBERS_ERROR = "FETCH_MEMBERS_ERROR";

export const CREATE_MEMBER = "CREATE_MEMBER";
export const CREATE_MEMBER_SUCCESS = "CREATE_MEMBER_SUCCESS";
export const CREATE_MEMBER_ERROR = "CREATE_MEMBER_ERROR";
