export const FETCH_SESSIONS = "FETCH_SESSIONS";
export const FETCH_SESSIONS_SUCCESS = "FETCH_SESSIONS_SUCCESS";
export const FETCH_SESSIONS_FAIL = "FETCH_SESSIONS_FAIL";

export const CREATE_SESSION = "CREATE_SESSION";
export const CREATE_SESSION_SUCCESS = "CREATE_SESSION_SUCCESS";
export const CREATE_SESSION_FAIL = "CREATE_SESSION_FAIL";

export const UPDATE_SESSION = "UPDATE_SESSION";
export const UPDATE_SESSION_SUCCESS = "UPDATE_SESSION_SUCCESS";
export const UPDATE_SESSION_FAIL = "UPDATE_SESSION_FAIL";

export const DELETE_SESSION = "DELETE_SESSION";
export const DELETE_SESSION_SUCCESS = "DELETE_SESSION_SUCCESS";
export const DELETE_SESSION_FAIL = "DELETE_SESSION_FAIL";

export const ENSURE_SESSIONS = "ENSURE_SESSIONS";
export const ENSURE_SESSIONS_SUCCESS = "ENSURE_SESSIONS_SUCCESS";
export const ENSURE_SESSIONS_FAIL = "ENSURE_SESSIONS_FAIL";
