export const FETCH_ATTENDANCE = "FETCH_ATTENDANCE";
export const FETCH_ATTENDANCE_SUCCESS = "FETCH_ATTENDANCE_SUCCESS";
export const FETCH_ATTENDANCE_FAIL = "FETCH_ATTENDANCE_FAIL";

export const MARK_ATTENDANCE = "MARK_ATTENDANCE";
export const MARK_ATTENDANCE_SUCCESS = "MARK_ATTENDANCE_SUCCESS";
export const MARK_ATTENDANCE_FAIL = "MARK_ATTENDANCE_FAIL";
