// Member constants based on external API schema
export const MEMBER_INITIAL_VALUE = {
  idMember: null,
  firstName: "",
  lastName: "",
  registerDate: null,
  accessBlocked: false,
  blockedReason: "",
  document: "",
  documentId: "",
  maritalStatus: "",
  gender: "",
  birthDate: null,
  country: "",
  address: "",
  state: "",
  city: "",
  zipCode: "",
  complement: "",
  neighborhood: "",
  number: "",
  passport: "",
  accessCardNumber: "",
  taxData: {
    firstName: "",
    lastName: "",
    email: "",
    direccion: "",
    dni: "",
    cuit: "",
    nit: "",
    taxType: null,
    personType: null,
    taxSystem: "",
    taxSystemDescription: "",
  },
  email: "",
  slug: "",
  penalized: false,
  membershipStatus: "",
  phone: "",
  contacts: [],
  lastAccessDate: null,
  responsibles: [],
  memberships: [],
  registrationKind: "",
  membership: null,
  photoUrl: "",
};

// Labels for potential form usage
export const MEMBER_FIELD_LABELS = {
  firstName: "Nome",
  lastName: "Sobrenome",
  email: "E-mail",
  document: "Documento",
  phone: "Telefone",
  cellphone: "Celular",
  birthDate: "Data de nascimento",
  address: "Endereço",
  state: "Estado",
  city: "Cidade",
  zipCode: "CEP",
  country: "País",
  neighborhood: "Bairro",
  number: "Número",
  complement: "Complemento",
};
