export const FETCH_AREAS = "FETCH_AREAS";
export const FETCH_AREAS_SUCCESS = "FETCH_AREAS_SUCCESS";
export const FETCH_AREAS_ERROR = "FETCH_AREAS_ERROR";

export const CREATE_AREA = "CREATE_AREA";
export const CREATE_AREA_SUCCESS = "CREATE_AREA_SUCCESS";
export const CREATE_AREA_ERROR = "CREATE_AREA_ERROR";

export const UPDATE_AREA = "UPDATE_AREA";
export const UPDATE_AREA_SUCCESS = "UPDATE_AREA_SUCCESS";
export const UPDATE_AREA_ERROR = "UPDATE_AREA_ERROR";

export const DELETE_AREA = "DELETE_AREA";
export const DELETE_AREA_SUCCESS = "DELETE_AREA_SUCCESS";
export const DELETE_AREA_ERROR = "DELETE_AREA_ERROR";
