// Topic Actions
export const FETCH_TOPICS = 'FETCH_TOPICS';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_ERROR = 'FETCH_TOPICS_ERROR';

export const CREATE_TOPIC = 'CREATE_TOPIC';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_ERROR = 'CREATE_TOPIC_ERROR';

export const UPDATE_TOPIC = 'UPDATE_TOPIC';
export const UPDATE_TOPIC_SUCCESS = 'UPDATE_TOPIC_SUCCESS';
export const UPDATE_TOPIC_ERROR = 'UPDATE_TOPIC_ERROR';

export const DELETE_TOPIC = 'DELETE_TOPIC';
export const DELETE_TOPIC_SUCCESS = 'DELETE_TOPIC_SUCCESS';
export const DELETE_TOPIC_ERROR = 'DELETE_TOPIC_ERROR';

// Clear errors
export const CLEAR_TOPIC_ERRORS = 'CLEAR_TOPIC_ERRORS';
