export const ENROLL_MEMBER = "ENROLL_MEMBER";
export const ENROLL_MEMBER_SUCCESS = "ENROLL_MEMBER_SUCCESS";
export const ENROLL_MEMBER_FAIL = "ENROLL_MEMBER_FAIL";

export const UNENROLL_MEMBER = "UNENROLL_MEMBER";
export const UNENROLL_MEMBER_SUCCESS = "UNENROLL_MEMBER_SUCCESS";
export const UNENROLL_MEMBER_FAIL = "UNENROLL_MEMBER_FAIL";

export const FETCH_ENROLLMENTS = "FETCH_ENROLLMENTS";
export const FETCH_ENROLLMENTS_SUCCESS = "FETCH_ENROLLMENTS_SUCCESS";
export const FETCH_ENROLLMENTS_FAIL = "FETCH_ENROLLMENTS_FAIL";
