export const FETCH_CONFIGS = "FETCH_CONFIGS";
export const FETCH_CONFIGS_SUCCESS = "FETCH_CONFIGS_SUCCESS";
export const FETCH_CONFIGS_FAIL = "FETCH_CONFIGS_FAIL";

export const CREATE_CONFIG = "CREATE_CONFIG";
export const CREATE_CONFIG_SUCCESS = "CREATE_CONFIG_SUCCESS";
export const CREATE_CONFIG_FAIL = "CREATE_CONFIG_FAIL";

export const UPDATE_CONFIG = "UPDATE_CONFIG";
export const UPDATE_CONFIG_SUCCESS = "UPDATE_CONFIG_SUCCESS";
export const UPDATE_CONFIG_FAIL = "UPDATE_CONFIG_FAIL";

export const DELETE_CONFIG = "DELETE_CONFIG";
export const DELETE_CONFIG_SUCCESS = "DELETE_CONFIG_SUCCESS";
export const DELETE_CONFIG_FAIL = "DELETE_CONFIG_FAIL";
