// Audit constants
export const AUDIT_ACTIONS = {
  // Employees
  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
  UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
  LOGIN_EMPLOYEE: 'LOGIN_EMPLOYEE',
  LOGOUT_EMPLOYEE: 'LOGOUT_EMPLOYEE',

  // Members
  CREATE_MEMBER: 'CREATE_MEMBER',
  UPDATE_MEMBER: 'UPDATE_MEMBER',
  DELETE_MEMBER: 'DELETE_MEMBER',
  LOGIN_MEMBER: 'LOGIN_MEMBER',
  LOGOUT_MEMBER: 'LOGOUT_MEMBER',

  // Memberships
  CREATE_MEMBERSHIP: 'CREATE_MEMBERSHIP',
  UPDATE_MEMBERSHIP: 'UPDATE_MEMBERSHIP',
  DELETE_MEMBERSHIP: 'DELETE_MEMBERSHIP',

  // Areas
  CREATE_AREA: 'CREATE_AREA',
  UPDATE_AREA: 'UPDATE_AREA',
  DELETE_AREA: 'DELETE_AREA',

  // Products
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',

  // Services
  CREATE_SERVICE: 'CREATE_SERVICE',
  UPDATE_SERVICE: 'UPDATE_SERVICE',
  DELETE_SERVICE: 'DELETE_SERVICE',

  // Evaluations
  CREATE_EVALUATION: 'CREATE_EVALUATION',
  UPDATE_EVALUATION: 'UPDATE_EVALUATION',
  DELETE_EVALUATION: 'DELETE_EVALUATION',
  CREATE_EVALUATION_LEVEL: 'CREATE_EVALUATION_LEVEL',
  UPDATE_EVALUATION_LEVEL: 'UPDATE_EVALUATION_LEVEL',
  DELETE_EVALUATION_LEVEL: 'DELETE_EVALUATION_LEVEL',
  CREATE_EVALUATION_OBJECTIVE: 'CREATE_EVALUATION_OBJECTIVE',
  UPDATE_EVALUATION_OBJECTIVE: 'UPDATE_EVALUATION_OBJECTIVE',
  DELETE_EVALUATION_OBJECTIVE: 'DELETE_EVALUATION_OBJECTIVE',
  CREATE_EVALUATION_TOPIC: 'CREATE_EVALUATION_TOPIC',
  UPDATE_EVALUATION_TOPIC: 'UPDATE_EVALUATION_TOPIC',
  DELETE_EVALUATION_TOPIC: 'DELETE_EVALUATION_TOPIC',

  // Activities
  CREATE_ACTIVITY: 'CREATE_ACTIVITY',
  UPDATE_ACTIVITY: 'UPDATE_ACTIVITY',
  DELETE_ACTIVITY: 'DELETE_ACTIVITY',

  // Activities Schedule
  CREATE_ACTIVITIES_SCHEDULE: 'CREATE_ACTIVITIES_SCHEDULE',
  UPDATE_ACTIVITIES_SCHEDULE: 'UPDATE_ACTIVITIES_SCHEDULE',
  DELETE_ACTIVITIES_SCHEDULE: 'DELETE_ACTIVITIES_SCHEDULE',
  VIEW_ACTIVITIES_SCHEDULE: 'VIEW_ACTIVITIES_SCHEDULE',

  // Activities Sessions
  CREATE_ACTIVITY_SESSION: 'CREATE_ACTIVITY_SESSION',
  UPDATE_ACTIVITY_SESSION: 'UPDATE_ACTIVITY_SESSION',
  DELETE_ACTIVITY_SESSION: 'DELETE_ACTIVITY_SESSION',

  // Photos
  UPLOAD_PHOTO: 'UPLOAD_PHOTO',
  DELETE_PHOTO: 'DELETE_PHOTO',

  // System
  EXPORT_DATA: 'EXPORT_DATA',
  IMPORT_DATA: 'IMPORT_DATA',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD'
};

export const AUDIT_RESOURCES = {
  EMPLOYEES: 'employees',
  MEMBERS: 'members',
  MEMBERSHIPS: 'memberships',
  AREAS: 'areas',
  PRODUCTS: 'products',
  SERVICES: 'services',
  EVALUATIONS: 'evaluations',
  EVALUATION_OBJECTIVES: 'evaluation_objectives',
  ACTIVITIES: 'activities',
  ACTIVITIES_SCHEDULE: 'activities_schedule',
  ACTIVITIES_SESSIONS: 'activities_sessions',
  PHOTOS: 'photos',
  SYSTEM: 'system'
};

// Audit log structure
export const AUDIT_LOG_STRUCTURE = {
  id: '',
  timestamp: null,
  userId: '',
  userEmail: '',
  userName: '',
  userRole: '',
  action: '',
  resource: '',
  resourceId: '',
  details: {},
  ipAddress: '',
  userAgent: ''
};
