// Objective Actions
export const FETCH_OBJECTIVES = 'FETCH_OBJECTIVES';
export const FETCH_OBJECTIVES_SUCCESS = 'FETCH_OBJECTIVES_SUCCESS';
export const FETCH_OBJECTIVES_ERROR = 'FETCH_OBJECTIVES_ERROR';

export const CREATE_OBJECTIVE = 'CREATE_OBJECTIVE';
export const CREATE_OBJECTIVE_SUCCESS = 'CREATE_OBJECTIVE_SUCCESS';
export const CREATE_OBJECTIVE_ERROR = 'CREATE_OBJECTIVE_ERROR';

export const UPDATE_OBJECTIVE = 'UPDATE_OBJECTIVE';
export const UPDATE_OBJECTIVE_SUCCESS = 'UPDATE_OBJECTIVE_SUCCESS';
export const UPDATE_OBJECTIVE_ERROR = 'UPDATE_OBJECTIVE_ERROR';

export const DELETE_OBJECTIVE = 'DELETE_OBJECTIVE';
export const DELETE_OBJECTIVE_SUCCESS = 'DELETE_OBJECTIVE_SUCCESS';
export const DELETE_OBJECTIVE_ERROR = 'DELETE_OBJECTIVE_ERROR';

// Clear errors
export const CLEAR_OBJECTIVE_ERRORS = 'CLEAR_OBJECTIVE_ERRORS';
